"""Builds stages 2-6 of Thornlash as ASCII block files (godot/content/levels/stageN.txt).

Stage 1 is hand-written; these are generated from the builder calls below so stair
geometry, landings and gaps are always consistent. The output files are the content the
game ships; this script is their source. All layouts are original.

Legend (see stage1.txt): # stone  = ledge  X breakable  / \\ stairs  ~ water  ^ spikes
  @ start  i/I/j candles  G/M/F spawn zones  E exit  Z boss trigger  letters = enemies
"""
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "godot" / "content" / "levels"


class Block:
    def __init__(self, bid, w, h, **meta):
        self.id, self.w, self.h = bid, w, h
        self.g = [["."] * w for _ in range(h)]
        self.meta = meta
        self.candles = []
        self.hidden = []

    def put(self, x, y, c):
        if 0 <= x < self.w and 0 <= y < self.h:
            self.g[y][x] = c

    def fill(self, x0, y0, x1, y1, c="#"):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                self.put(x, y, c)

    def ground(self, x0, x1, top, c="#"):
        """Solid from row `top` down to the bottom of the block."""
        self.fill(x0, top, x1, self.h - 1, c)

    def ledge(self, x0, x1, y, c="="):
        self.fill(x0, y, x1, y, c)

    def stair_up_right(self, x, floor_row, n):
        """'/' from the floor at `floor_row` (row of the floor tiles) rising n steps to the right.
        Returns (landing_x, landing_row): place the landing floor there."""
        for i in range(n):
            self.put(x + i, floor_row - 1 - i, "/")
        return x + n, floor_row - n

    def stair_up_left(self, x, floor_row, n):
        """'\\' whose bottom cell is (x, floor_row-1), rising n steps to the left."""
        for i in range(n):
            self.put(x - i, floor_row - 1 - i, "\\")
        return x - n, floor_row - n

    def clear(self, x0, y0, x1, y1):
        self.fill(x0, y0, x1, y1, ".")

    def candle(self, x, y, drop, kind="j"):
        self.put(x, y, kind)
        self.candles.append((y, x, drop))

    def wall_x(self, x, y, drop="-"):
        self.put(x, y, "X")
        self.hidden.append((y, x, drop))

    def text(self):
        meta = dict(self.meta)
        # candle drops and hidden items are listed in reading order (row, then column)
        # keep only candles and walls that survived later edits (a stair may overwrite one)
        live = [(y, x, d) for (y, x, d) in self.candles if self.g[y][x] in "iIj"]
        walls = [(y, x, d) for (y, x, d) in self.hidden if self.g[y][x] == "X"]
        meta["candles"] = ",".join(d for _, _, d in sorted(live))
        meta["hidden"] = ",".join(d for _, _, d in sorted(walls))
        lines = [f"@block {self.id}"]
        for k, v in meta.items():
            if v != "" and v is not None:
                lines.append(f"{k}={v}")
        lines.append("---")
        lines += ["".join(r) for r in self.g]
        return "\n".join(lines) + "\n"


def write_stage(n, title, blocks):
    head = f"; Stage {n} - {title}. Generated by tools/levels/build_levels.py (original layout).\n\n"
    (OUT / f"stage{n}.txt").write_text(head + "\n".join(b.text() for b in blocks), encoding="utf8", newline="\n")
    print(f"stage{n}: " + ", ".join(f"{b.id} {b.w}x{b.h}" for b in blocks))


# ======================================================================== Stage 2: The Catacombs

def stage2():
    a = Block("2-1", 84, 12, name="Ossuary Gate", title="The Catacombs", area="catacomb", music="stage2",
              time=300, next="2-2")
    a.fill(0, 0, 83, 0)
    a.ground(0, 30, 7)                      # upper floor at row 7 (feet y = 112)
    a.put(2, 6, "@")
    for x, d in ((6, "heart"), (14, "bigheart"), (22, "heart")):
        a.candle(x, 5, d)
    a.put(20, 6, "S")
    # stairs down from the upper floor to the lower hall (row 10)
    a.clear(31, 7, 36, 9)
    a.ground(31, 83, 10)
    lx, lr = a.stair_up_left(36, 10, 3)     # bottom cell (36,9) rising left to landing (33, 7)
    a.put(33, 7, "#")
    a.put(32, 7, "#")
    a.put(31, 7, "#")
    a.put(26, 2, "B")
    a.put(44, 3, "B")
    a.put(50, 9, "S")
    a.put(64, 9, "Q")
    a.candle(42, 7, "whip")
    a.candle(52, 7, "heart")
    a.candle(58, 7, "flask")
    a.candle(70, 7, "bigheart")
    a.put(40, 9, "G")
    a.fill(83, 1, 83, 9)
    a.put(82, 8, "E")
    a.put(82, 9, "E")

    b = Block("2-2", 104, 12, name="Flooded Crypt", area="catacomb", music="stage2", next="2-3")
    b.fill(0, 0, 103, 0)
    b.fill(0, 10, 103, 11, "~")             # black water across the whole crypt floor
    b.ground(0, 9, 8)
    b.put(2, 7, "@")
    # stepping-stone piers with 2-tile gaps
    x = 12
    piers = []
    while x < 92:
        wdt = 3 if (x // 12) % 2 else 4
        b.ground(x, x + wdt - 1, 8)
        piers.append((x, wdt))
        x += wdt + 2
    b.ground(92, 103, 8)
    b.put(20, 10, "F")
    b.put(52, 10, "F")
    b.put(80, 10, "F")
    for i, (px, wdt) in enumerate(piers[::3]):
        b.candle(px + 1, 5, ["heart", "bigheart", "axe", "heart", "bag400", "heart"][i % 6])
    b.put(40, 3, "M")
    b.put(34, 2, "B")
    b.put(70, 2, "B")
    # a raised crypt shelf over the water with a breakable wall hiding a roast
    b.ledge(60, 70, 4)
    b.wall_x(71, 4, "roast")
    b.wall_x(71, 3, "-")
    b.candle(64, 2, "heart")
    b.fill(103, 1, 103, 7)
    b.put(102, 6, "E")
    b.put(102, 7, "E")

    c = Block("2-3", 70, 12, name="Charnel Deep", area="catacomb", music="stage2", next="",
              boss="wyrm", arena=50)
    c.fill(0, 0, 69, 0)
    c.ground(0, 69, 10)
    c.put(2, 9, "@")
    c.fill(10, 8, 14, 9, "%")               # bone-brick tombs to jump over
    c.fill(26, 8, 29, 9, "%")
    c.put(20, 9, "S")
    c.put(36, 9, "K")
    for x, d in ((8, "heart"), (18, "bigheart"), (32, "heart"), (44, "cross"), (55, "heart"), (65, "bigheart")):
        c.candle(x, 7, d)
    c.put(52, 9, "Z")
    return [a, b, c]


# ======================================================================== Stage 3: The Ramparts

def stage3():
    a = Block("3-1", 96, 12, name="Western Rampart", title="The Ramparts", area="rampart", music="stage3",
              time=300, next="3-2")
    a.ground(0, 95, 10)
    a.put(2, 9, "@")
    # crenellated parapet: merlons along the wall edge to hop over
    for x in range(12, 90, 10):
        a.fill(x, 8, x + 1, 9)
    a.clear(38, 10, 40, 11)                 # fallen sections of the wall walk
    a.clear(66, 10, 68, 11)
    for x in (18, 30, 50, 60, 78):
        a.put(x, 3, "R")
    a.put(46, 9, "W")
    a.put(84, 9, "W")
    for i, x in enumerate(range(6, 92, 11)):
        a.candle(x, 6, ["heart", "bigheart", "whip", "heart", "dagger", "bigheart", "heart", "double", "heart"][i % 9], "I")
    a.fill(95, 0, 95, 9)
    a.put(94, 8, "E")
    a.put(94, 9, "E")

    # vertical block: climb the tower by zig-zag stairs
    t = Block("3-2", 22, 36, name="Tower Climb", area="tower", music="stage3", next="3-3")
    t.fill(0, 0, 0, 35)
    t.fill(21, 0, 21, 35)
    t.ground(1, 20, 34)
    t.put(3, 33, "@")
    floor = 34
    x = 4
    right = True
    level = 0
    while floor > 8:
        if right:
            lx, lr = t.stair_up_right(x, floor, 5)
            t.ledge(lx, 20, lr)
            t.candle(15, lr - 2, ["heart", "bigheart", "heart", "potion", "heart"][level % 5])
            x = 16
        else:
            lx, lr = t.stair_up_left(x, floor, 5)
            t.ledge(1, lx, lr)
            t.candle(4, lr - 2, ["heart", "bigheart", "heart", "rosary", "heart"][level % 5])
            x = 5
        floor = lr
        right = not right
        level += 1
    t.put(10, 20, "M")
    t.put(12, 12, "N")
    t.put(10, floor - 1, "E")
    t.put(11, floor - 1, "E")
    t.put(10, floor - 2, "E")

    c = Block("3-3", 72, 12, name="Lantern Bridge", area="rampart", music="stage3", next="",
              boss="warden", arena=52)
    c.ground(0, 71, 10)
    c.put(2, 9, "@")
    c.clear(14, 10, 15, 11)
    c.clear(28, 10, 30, 11)
    c.put(22, 3, "R")
    c.put(36, 9, "K")
    for x, d in ((8, "heart"), (20, "bigheart"), (34, "heart"), (46, "axe"), (58, "heart"), (66, "bigheart")):
        c.candle(x, 6, d, "I")
    c.put(55, 9, "Z")
    return [a, t, c]


# ======================================================================== Stage 4: The Dungeons

def stage4():
    a = Block("4-1", 90, 12, name="The Oubliette", title="The Dungeons", area="dungeon", music="stage4",
              time=300, next="4-2")
    a.fill(0, 0, 89, 1)
    a.ground(0, 89, 10)
    a.put(2, 9, "@")
    a.fill(18, 2, 20, 5)                    # hanging masonry forces a crouch-free squeeze
    a.ledge(30, 44, 6)
    lx, lr = a.stair_up_right(26, 10, 4)
    a.ledge(lx, 44, lr)
    a.stair_up_left(48, 10, 4)
    a.put(24, 9, "H")
    a.put(38, 5, "H")
    a.put(54, 9, "Q")
    a.put(70, 9, "H")
    a.put(78, 9, "Q")
    for x, d in ((8, "heart"), (22, "whip"), (34, "bigheart"), (52, "heart"), (62, "flask"), (74, "heart"), (84, "bigheart")):
        a.candle(x, 7, d)
    a.fill(89, 2, 89, 9)
    a.put(88, 8, "E")
    a.put(88, 9, "E")

    b = Block("4-2", 100, 12, name="Rack Galleries", area="dungeon", music="stage4", next="4-3")
    b.fill(0, 0, 99, 1)
    b.ground(0, 99, 10)
    b.put(2, 9, "@")
    for x0 in (16, 40, 70):                 # spike pits under narrow walks
        b.fill(x0, 10, x0 + 4, 10, "^")
        b.fill(x0, 11, x0 + 4, 11, "#")
        b.clear(x0, 9, x0 + 4, 9)
        b.ledge(x0 + 1, x0 + 3, 7)
    b.put(28, 9, "P")
    b.put(58, 9, "P")
    b.put(86, 9, "O")
    b.put(50, 9, "Q")
    for x, d in ((8, "heart"), (24, "bigheart"), (34, "heart"), (46, "glass"), (64, "heart"), (80, "bigheart"), (92, "heart")):
        b.candle(x, 7, d)
    b.wall_x(95, 9, "roast")
    b.wall_x(95, 8, "-")
    b.fill(99, 2, 99, 9)
    b.put(98, 8, "E")
    b.put(98, 9, "E")

    c = Block("4-3", 66, 12, name="Gaoler's Pit", area="dungeon", music="stage4", next="",
              boss="chainmaster", arena=46)
    c.fill(0, 0, 65, 1)
    c.ground(0, 65, 10)
    c.put(2, 9, "@")
    c.put(18, 9, "P")
    c.put(30, 9, "H")
    for x, d in ((8, "heart"), (16, "bigheart"), (26, "heart"), (38, "dagger"), (50, "heart"), (60, "bigheart")):
        c.candle(x, 7, d)
    c.put(49, 9, "Z")
    return [a, b, c]


# ======================================================================== Stage 5: The Clockwork Spire

def stage5():
    a = Block("5-1", 92, 12, name="Gear Hall", title="The Clockwork Spire", area="clock", music="stage5",
              time=300, next="5-2")
    a.ground(0, 91, 10)
    a.put(2, 9, "@")
    for i, x0 in enumerate(range(14, 84, 14)):
        a.ledge(x0, x0 + 5, 6 if i % 2 else 7)
    a.clear(34, 10, 36, 11)
    a.clear(62, 10, 64, 11)
    a.put(20, 4, "R")
    a.put(44, 9, "H")
    a.put(56, 4, "N")
    a.put(74, 9, "H")
    a.put(80, 3, "R")
    for i, x in enumerate(range(8, 88, 10)):
        a.candle(x, 4, ["heart", "bigheart", "whip", "heart", "cross", "heart", "triple", "bigheart"][i % 8])
    a.fill(91, 0, 91, 9)
    a.put(90, 8, "E")
    a.put(90, 9, "E")

    t = Block("5-2", 24, 40, name="Pendulum Shaft", area="clock", music="stage5", next="5-3")
    t.fill(0, 0, 0, 39)
    t.fill(23, 0, 23, 39)
    t.ground(1, 22, 38)
    t.put(3, 37, "@")
    floor = 38
    x = 4
    right = True
    level = 0
    while floor > 8:
        n = 4 if level % 2 else 5
        if right:
            lx, lr = t.stair_up_right(x, floor, n)
            t.ledge(lx, 22, lr)
            t.candle(18, lr - 2, ["heart", "bigheart", "heart", "rosary"][level % 4])
            x = 17
        else:
            lx, lr = t.stair_up_left(x, floor, n)
            t.ledge(1, lx, lr)
            t.candle(4, lr - 2, ["heart", "bigheart", "potion", "heart"][level % 4])
            x = 6
        floor = lr
        right = not right
        level += 1
    t.put(12, 26, "M")
    t.put(10, 16, "N")
    t.put(12, 30, "N")
    t.put(11, floor - 1, "E")
    t.put(12, floor - 1, "E")
    t.put(11, floor - 2, "E")

    c = Block("5-3", 70, 12, name="The Clock Face", area="clock", music="stage5", next="",
              boss="horologist", arena=50)
    c.ground(0, 69, 10)
    c.put(2, 9, "@")
    c.ledge(12, 18, 7)
    c.ledge(24, 30, 6)
    c.put(20, 9, "H")
    c.put(34, 9, "P")
    for x, d in ((8, "heart"), (15, "bigheart"), (27, "heart"), (40, "flask"), (56, "heart"), (64, "bigheart")):
        c.candle(x, 4, d)
    c.put(53, 9, "Z")
    return [a, t, c]


# ======================================================================== Stage 6: The Throne of Ash

def stage6():
    a = Block("6-1", 100, 12, name="Long Gallery", title="The Throne of Ash", area="throne", music="stage6",
              time=400, next="6-2")
    a.fill(0, 0, 99, 0)
    a.ground(0, 99, 10)
    a.put(2, 9, "@")
    for x in (20, 44, 68):
        a.put(x, 9, "O")
    a.put(30, 9, "P")
    a.put(56, 9, "P")
    a.put(80, 9, "Q")
    a.put(36, 3, "N")
    a.put(74, 3, "N")
    for i, x in enumerate(range(6, 96, 9)):
        a.candle(x, 6, ["heart", "bigheart", "whip", "heart", "axe", "heart", "double", "bigheart", "heart", "roast"][i % 10], "I")
    a.fill(99, 1, 99, 9)
    a.put(98, 8, "E")
    a.put(98, 9, "E")

    b = Block("6-2", 72, 24, name="Stair of Ash", area="throne", music="stage6", next="6-3")
    b.fill(0, 0, 71, 0)
    b.ground(0, 16, 22)
    b.put(2, 21, "@")
    # one long ascent in three flights with landings
    lx, lr = b.stair_up_right(10, 22, 6)
    b.ground(lx, lx + 6, lr)
    lx2, lr2 = b.stair_up_right(lx + 7, lr, 6)
    b.ground(lx2, lx2 + 6, lr2)
    lx3, lr3 = b.stair_up_right(lx2 + 7, lr2, 6)
    b.ground(lx3, 71, lr3)
    b.put(26, 8, "M")
    b.put(44, 4, "M")
    b.put(lx + 3, lr - 1, "Q")
    b.put(lx2 + 3, lr2 - 1, "P")
    b.put(lx3 + 8, lr3 - 1, "P")
    for i, (x, y) in enumerate(((6, 19), (lx + 2, lr - 3), (lx + 5, lr - 3), (lx2 + 2, lr2 - 3), (lx2 + 5, lr2 - 3),
                                 (lx3 + 4, lr3 - 3), (lx3 + 12, lr3 - 3))):
        b.candle(x, y, ["heart", "bigheart", "heart", "glass", "bigheart", "heart", "roast"][i])
    b.fill(71, 0, 71, lr3 - 1)
    b.put(70, lr3 - 1, "E")
    b.put(70, lr3 - 2, "E")

    c = Block("6-3", 48, 12, name="Throne of Ash", area="throne", music="stage6", next="",
              boss="margrave", arena=28)
    c.fill(0, 0, 47, 0)
    c.ground(0, 47, 10)
    c.put(2, 9, "@")
    for x, d in ((8, "bigheart"), (16, "heart"), (22, "roast")):
        c.candle(x, 6, d, "I")
    c.put(31, 9, "Z")
    return [a, b, c]


if __name__ == "__main__":
    write_stage(2, "The Catacombs", stage2())
    write_stage(3, "The Ramparts", stage3())
    write_stage(4, "The Dungeons", stage4())
    write_stage(5, "The Clockwork Spire", stage5())
    write_stage(6, "The Throne of Ash", stage6())
