// PC-speaker style sound effects: WAVs generated by pipeline/audio/make_sfx.py,
// listed in content/sfx/sfx.json. Browsers need a user gesture before audio, so
// the context is created on the first key or click.

function fromDataUri(uri) {
  const bin = atob(uri.slice(uri.indexOf(',') + 1));
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes.buffer;
}

export class Sound {
  constructor(index, base = '../content/sfx/') {
    this.index = index || {};
    this.base = base;
    this.enabled = true;
    this.ctx = null;
    this.buffers = {};
  }

  async unlock() {
    if (this.ctx) return;
    try {
      this.ctx = new (window.AudioContext || window.webkitAudioContext)();
    } catch (e) { this.ctx = null; return; }
    for (const [name, file] of Object.entries(this.index)) {
      try {
        const b = window.__BUNDLE__ && window.__BUNDLE__['sfx/' + file];
        // bundled WAVs are decoded in place: an artifact's CSP may refuse fetch() of data: URLs
        const data = b ? fromDataUri(b) : await (await fetch(this.base + file)).arrayBuffer();
        this.buffers[name] = await this.ctx.decodeAudioData(data);
      } catch (e) { /* a missing effect is silent, never fatal */ }
    }
  }

  play(name) {
    if (!this.enabled || !this.ctx || !this.buffers[name]) return;
    const src = this.ctx.createBufferSource();
    src.buffer = this.buffers[name];
    const gain = this.ctx.createGain();
    gain.gain.value = 0.35;
    src.connect(gain).connect(this.ctx.destination);
    src.start();
  }

  toggle() { this.enabled = !this.enabled; return this.enabled; }
}
